### PR TITLE
Create Crud For Students

### PR DESCRIPTION
**Pull request by Hazeem01**
## What does this Code do? ##
-Create CRUD endpoints For Students

### Description of tasks to be completed? ###
It makes sure that the following routes are working:
GET  /api/students/home
GET  /api/students/
GET  /api/students/`id`
POST  /api/students
PUT  /api/students/`id`
DELETE /api/students/`id`

### How should this be manually tested/checked? ###
- Clone the PR
- Checkout to the branch `create-crud-for-students`
- Install the dependencies using `npm install`
- Create a `.env` file and define the following as follows:
   - `PORT = 3000`
   - `database = <your database name>`
   - ` username = <your username>`
   - ` host = 127.0.0.1`
    - ` dialect = postgres`
- Start the server by running `npm start`
- To test this feature, go to--> http://localhost:3000/ `<any of the routes>` on postman.

### CODE REVIEW

**Review by bellogo — COMMENTED** [review]
kindly add a description for your pull request

**Review by Ekemiben — COMMENTED** [review]
Your model does not have all the attributes.

**Comment by Hazeem01** [comment]
> Your model does not have all the attributes.

**Comment by bellogo** [comment]
Fix the errors causing the server not to run

**Review by Ekemiben — APPROVED** [review]

**Review by Ekemiben — APPROVED** [review]

**Review by Ekemiben — APPROVED** [review]

**Pull request merged**
